import { describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

import type {
  ClaimedResearchJob,
  JobExecutionError,
} from "@/lib/jobs/contracts";
import type { ResearchJobRepository } from "@/lib/jobs/repository";
import { processNextResearchJob } from "@/lib/jobs/worker";

const job: ClaimedResearchJob = {
  id: "11111111-1111-4111-8111-111111111111",
  projectId: "22222222-2222-4222-8222-222222222222",
  requestedBy: "33333333-3333-4333-8333-333333333333",
  provider: "apify",
  input: {
    query: "creator tools",
    maxCompetitors: 1,
    apify: {
      searchQueries: ["creator tools"],
      maxResults: 1,
      maxResultsShorts: 0,
      maxResultStreams: 0,
      startUrls: [],
      downloadSubtitles: false,
      subtitlesLanguage: "en",
      subtitlesFormat: "srt",
      aiVideoDescription: false,
      aiVideoSummary: false,
      saveSubsToKVS: false,
      preferAutoGeneratedSubtitles: false,
    },
  },
  attemptCount: 1,
  maxAttempts: 3,
  leaseOwner: "worker-1",
  leaseExpiresAt: "2026-08-01T08:05:00.000Z",
};

function repositoryFor(claimed: ClaimedResearchJob | null = job) {
  return {
    enqueue: vi.fn(),
    claimNext: vi.fn().mockResolvedValue(claimed),
    heartbeat: vi.fn().mockResolvedValue(undefined),
    complete: vi.fn().mockResolvedValue(undefined),
    failOrRetry: vi.fn().mockResolvedValue("retried"),
  } satisfies ResearchJobRepository;
}

describe("processNextResearchJob", () => {
  it("claims, executes, and completes one durable job", async () => {
    const repository = repositoryFor();
    const result = {
      runId: "run-1",
      datasetId: "dataset-1",
      status: "SUCCEEDED" as const,
      items: [],
    };

    await expect(
      processNextResearchJob(
        "worker-1",
        repository,
        vi.fn().mockResolvedValue(result),
      ),
    ).resolves.toEqual({ status: "completed", jobId: job.id });
    expect(repository.complete).toHaveBeenCalledWith(job, result);
    expect(repository.failOrRetry).not.toHaveBeenCalled();
  });

  it("persists resume identifiers from a retryable post-run failure", async () => {
    const repository = repositoryFor();
    const failure: JobExecutionError = {
      code: "PROVIDER_ERROR",
      message: "Dataset retrieval timed out.",
      retryable: true,
      runId: "run-1",
      datasetId: "dataset-1",
    };

    const result = await processNextResearchJob(
      "worker-1",
      repository,
      vi.fn().mockRejectedValue(failure),
    );

    expect(result).toMatchObject({ status: "retried", error: failure });
    expect(repository.failOrRetry).toHaveBeenCalledWith(
      job,
      failure,
      expect.any(String),
    );
  });

  it("does no provider work when the queue is empty", async () => {
    const repository = repositoryFor(null);
    const execute = vi.fn();
    await expect(
      processNextResearchJob("worker-1", repository, execute),
    ).resolves.toEqual({
      status: "idle",
    });
    expect(execute).not.toHaveBeenCalled();
  });
});
