import { z } from "zod";

const youtubeUrlSchema = z
  .url()
  .refine(
    (url) => {
      const hostname = new URL(url).hostname;
      return hostname === "youtube.com" || hostname.endsWith(".youtube.com");
    },
    { message: "Direct URLs must use a youtube.com host." },
  );

export const apifyYouTubeActorInputSchema = z
  .object({
    searchQueries: z
      .array(z.string().trim().min(1).max(500))
      .max(50)
      .default([]),
    maxResults: z.number().int().min(0).max(999_999).default(0),
    maxResultsShorts: z.number().int().min(0).max(999_999).default(0),
    maxResultStreams: z.number().int().min(0).max(999_999).default(0),
    startUrls: z
      .array(z.object({ url: youtubeUrlSchema }).strict())
      .max(100)
      .default([]),
    downloadSubtitles: z.boolean().default(false),
    subtitlesLanguage: z
      .enum(["any", "en", "de", "es", "fr", "it", "ja", "ko", "nl", "pt", "ru"])
      .default("en"),
    subtitlesFormat: z.enum(["srt", "vtt", "xml", "plaintext"]).default("srt"),
    sortingOrder: z
      .enum(["relevance", "rating", "date", "views"])
      .nullable()
      .optional(),
    dateFilter: z
      .enum(["hour", "today", "week", "month", "year"])
      .nullable()
      .optional(),
    videoType: z.enum(["video", "movie"]).nullable().optional(),
    lengthFilter: z
      .enum(["under4", "between420", "plus20"])
      .nullable()
      .optional(),
    oldestPostDate: z
      .string()
      .regex(
        /^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])(T[0-2]\d:[0-5]\d(:[0-5]\d)?(\.\d+)?Z?)?$|^(\d+)\s*(minute|hour|day|week|month|year)s?$/,
      )
      .optional(),
    sortVideosBy: z.enum(["NEWEST", "POPULAR", "OLDEST"]).optional(),
    aiVideoDescription: z.boolean().default(false),
    aiVideoSummary: z.boolean().default(false),
    saveSubsToKVS: z.boolean().default(false),
    preferAutoGeneratedSubtitles: z.boolean().default(false),
  })
  .strict()
  .refine(
    ({ searchQueries, startUrls }) =>
      searchQueries.length > 0 || startUrls.length > 0,
    { message: "At least one search query or direct YouTube URL is required." },
  )
  .refine(
    ({ maxResults, maxResultsShorts, maxResultStreams }) =>
      maxResults + maxResultsShorts + maxResultStreams > 0,
    { message: "At least one result limit must be greater than zero." },
  )
  .refine(
    ({ downloadSubtitles, saveSubsToKVS }) =>
      downloadSubtitles || !saveSubsToKVS,
    {
      message: "Saving subtitles to KVS requires subtitle downloads.",
      path: ["saveSubsToKVS"],
    },
  )
  .refine(
    ({ downloadSubtitles, preferAutoGeneratedSubtitles }) =>
      downloadSubtitles || !preferAutoGeneratedSubtitles,
    {
      message:
        "Preferring auto-generated subtitles requires subtitle downloads.",
      path: ["preferAutoGeneratedSubtitles"],
    },
  );

const nullableMetricSchema = z.number().nonnegative().nullable();

export const apifyYouTubeDatasetItemSchema = z
  .object({
    id: z.string().min(1),
    url: z.url(),
    title: z.string().min(1),
    type: z.string().min(1),
    thumbnailUrl: z.url().nullable().optional(),
    viewCount: nullableMetricSchema,
    date: z.string().min(1),
    likes: nullableMetricSchema,
    channelName: z.string().min(1),
    channelUrl: z.url(),
    channelUsername: z.string().nullable().optional(),
    channelId: z.string().min(1),
    numberOfSubscribers: nullableMetricSchema,
    duration: z.string().nullable(),
    commentsCount: nullableMetricSchema,
    text: z.string().nullable().optional(),
    subtitles: z.array(z.record(z.string(), z.unknown())).nullable().optional(),
    aiVideoDescription: z.unknown().nullable().optional(),
    aiVideoSummary: z.unknown().nullable().optional(),
  })
  .loose();

export type ApifyYouTubeActorInput = z.input<
  typeof apifyYouTubeActorInputSchema
>;
export type ParsedApifyYouTubeActorInput = z.output<
  typeof apifyYouTubeActorInputSchema
>;
export type ApifyYouTubeDatasetItem = z.infer<
  typeof apifyYouTubeDatasetItemSchema
>;
