import { describe, expect, it } from "vitest";

import {
  apifyYouTubeActorInputSchema,
  apifyYouTubeDatasetItemSchema,
  apifyYouTubeExecutionFailureSchema,
  apifyYouTubeRunReferenceSchema,
} from "@/lib/contracts/apify";

describe("apifyYouTubeActorInputSchema", () => {
  it("accepts the documented Actor options", () => {
    const result = apifyYouTubeActorInputSchema.safeParse({
      searchQueries: ["AI creator workflows"],
      maxResults: 5,
      maxResultsShorts: 2,
      maxResultStreams: 1,
      startUrls: [],
      downloadSubtitles: true,
      subtitlesLanguage: "en",
      subtitlesFormat: "plaintext",
      sortingOrder: "views",
      dateFilter: "month",
      videoType: "video",
      lengthFilter: "between420",
      oldestPostDate: "2 months",
      sortVideosBy: "POPULAR",
      aiVideoDescription: false,
      aiVideoSummary: false,
      saveSubsToKVS: true,
      preferAutoGeneratedSubtitles: true,
    });

    expect(result.success).toBe(true);
  });

  it("requires a source and a non-zero result limit", () => {
    expect(
      apifyYouTubeActorInputSchema.safeParse({
        searchQueries: [],
        startUrls: [],
        maxResults: 0,
      }).success,
    ).toBe(false);
  });

  it("rejects subtitle storage without subtitle downloads", () => {
    expect(
      apifyYouTubeActorInputSchema.safeParse({
        searchQueries: ["creator economy"],
        maxResults: 1,
        saveSubsToKVS: true,
      }).success,
    ).toBe(false);
  });
});

describe("apifyYouTubeDatasetItemSchema", () => {
  it("validates evidence fields while allowing new Actor fields", () => {
    const result = apifyYouTubeDatasetItemSchema.safeParse({
      id: "video-id",
      url: "https://www.youtube.com/watch?v=video-id",
      title: "A useful video",
      type: "video",
      viewCount: 123,
      date: "2026-07-01T00:00:00.000Z",
      likes: 10,
      channelName: "Example Channel",
      channelUrl: "https://www.youtube.com/channel/channel-id",
      channelId: "channel-id",
      numberOfSubscribers: 1_000,
      duration: "00:10:00",
      commentsCount: 2,
      upstreamAddition: true,
    });

    expect(result.success).toBe(true);
  });
});

describe("Apify durable worker contracts", () => {
  it("validates persisted resume references", () => {
    expect(
      apifyYouTubeRunReferenceSchema.parse({
        runId: "run-id",
        datasetId: "dataset-id",
      }),
    ).toEqual({ runId: "run-id", datasetId: "dataset-id" });
  });

  it("validates retryable failures with provider resume metadata", () => {
    expect(
      apifyYouTubeExecutionFailureSchema.safeParse({
        code: "PROVIDER_ERROR",
        message: "The Apify dataset request failed.",
        retryable: true,
        runId: "run-id",
        datasetId: "dataset-id",
      }).success,
    ).toBe(true);
  });
});
